### ISSUE TITLE
Placing a torch on a ore which a level restriction eats the torch

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Skills#18]
Example:  if you have a lvl 60 requirement on an ore,  if you place a torch on the ore, the ore errors, says needs lvl 60, then eats the torch.

**Comment by Zidane** [comment]
@Dockter This is a Sponge bug with the tracker.

**Comment by TherayTharow** [comment]
it also does this on ic2 machines

**Comment by Zidane** [comment]
Fixed in latest SpongeForge.
